/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hardsid_builder_HsidDLL2 */

#ifndef _Included_hardsid_builder_HsidDLL2
#define _Included_hardsid_builder_HsidDLL2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    LoadLibrary
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_hardsid_1builder_HsidDLL2_LoadLibrary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    InitHardSID_Mapper
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_InitHardSID_1Mapper
  (JNIEnv *, jobject);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Version
  (JNIEnv *, jobject);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Delay
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Delay
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Devices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Devices
  (JNIEnv *, jobject);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Filter
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Filter
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Flush
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Flush
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_MuteAll
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1MuteAll
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Read
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Read
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Sync
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Sync
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Write
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Write
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Reset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Lock
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Lock
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Unlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Unlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Reset2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Reset2
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Mute
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Mute
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_Mute2
 * Signature: (IIZZ)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1Mute2
  (JNIEnv *, jobject, jint, jint, jboolean, jboolean);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    HardSID_SoftFlush
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_HardSID_1SoftFlush
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    MuteHardSID_Line
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_MuteHardSID_1Line
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    ReadFromHardSID
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hardsid_1builder_HsidDLL2_ReadFromHardSID
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    WriteToHardSID
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_WriteToHardSID
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    SetDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_hardsid_1builder_HsidDLL2_SetDebug
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hardsid_builder_HsidDLL2
 * Method:    GetHardSIDCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hardsid_1builder_HsidDLL2_GetHardSIDCount
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
