// Source generated by DCC6502 version v2.0
// For more info about DCC6502, see https://github.com/tcarmelveilleux/dcc6502
// FILENAME: ../../Documents/sidplayer1.prg, File Size: 3218, ORG: $E000
//---------------------------------------------------------------------------
.pc = $E000
.fill $015f,0

.byte $61, $E1, $60, $01, $02, $04, $00, $07
.byte $0E, $02, $02, $FE, $02, $02, $FE, $FE
.byte $00, $01, $00, $FF, $00, $02, $04, $05
.byte $07, $09, $0B, $1E, $18, $8B, $7E, $FA
.byte $06, $AC, $F3, $E6, $8F, $F8, $2E, $86
.byte $8E, $96, $9F, $A8, $B3, $BD, $C8, $D4
.byte $E1, $EE, $FD, $8C, $78, $64, $50, $3C
.byte $28, $14, $00, $00, $02, $03, $05, $07
.byte $08, $0A, $0C, $0D, $0F, $11, $12, $00
.byte $E0, $00, $05, $0A, $0F, $F9, $00, $F5
.byte $00, $00, $00, $10, $00, $00, $20, $00
.byte $00, $30, $00, $00, $40, $00, $00, $50
.byte $00, $00, $60, $00, $00, $70, $00, $00
.byte $80, $00, $00, $90, $00, $00

        ldy #$00
        lda #$00
        sta $e000
        ldx #$95
        ldy #$42
        lda $02a6
        beq l1
        ldx #$25
        ldy #$40
l1:
        stx $e15b
        sty $e15c

        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop

        rts
        lda #$00
        sta $e000
        stx $61
        sty $62
        ldy #$bc
l2:
        sta $e000,y
        dey
        bne l2

        ldy #$72
l3:
        sta $e0bc,y
        dey
        bne l3

        sta $d415
        sta $d416
        lda #$08
        sta $e025
        sta $d417
        sta $e026
        sta $d418
        lda #$90
        sta $e027
        lda #$60
        sta $e028
        lda #$0c
        sta $e029
        lda $e15b
        sta $e02d
        lda $e15c
        sta $e02e
        lda #$ff
        sta $e0cc
        lda #$d4
        sta $64
        ldx #$02
l4:
        lda #$ff
        sta $e00b,x
        lda #$01
        sta $e030,x
        sta $e02a,x
        txa
        sta $e033,x
        sta $e0ae,x
        lda #$04
        sta $e039,x
        lda $e1a8,x
        sta $e0ba,x
        lda #$5b
        sta $e07e,x
        lda $e165,x
        sta $63
        lda #$00
        tay
        sta ($63),y
        iny
        sta ($63),y
        iny
        sta ($63),y
        lda #$08
        sta $e017,x
        sta $e09c,x
        iny
        sta ($63),y
        iny
        sta ($63),y
        lda #$40
        sta $e01a,x
        sta ($63),y
        lda #$20
        sta $e01d,x
        iny
        sta ($63),y
        lda #$f5
        sta $e020,x
        iny
        sta ($63),y
        dex
        bpl l4

        txa
        ldx #$17
l5:
        sta $e13e,x
        dex
        bpl l5
        lda $61
        clc
        adc #$06
        sta $63
        lda #$00
        tax
        tay
        adc $62
l6:
        sta $64
        sta $e0ab,x
        sta $e0b4,x
        lda $63
        sta $e0a8,x
        sta $e0b1,x
        clc
        adc ($61),y
        sta $63
        lda $64
        iny
        adc ($61),y
        iny
        inx
        cpx #$03
        bne l6

        ldx $63
        tay
        rts
        lda #$00
        sta $d404
        sta $d40b
        sta $d412
        sta $d401
        sta $d408
        sta $d40f
        lda #$08
        sta $d417
        lda $e15b
        sta $dc04
        lda $e15c
        sta $dc05
        rts

        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop

        rts
l7:
        lda #$08
        sta $e000
l8:
        jmp ($e15d)
        nop
        nop
        nop
        lda $e000
        bmi l7
        ora #$80
        tay
        and #$07
        beq l8
        cld
        sty $e000
        nop
        lda $fb
        sta $e156
        lda $fc
        sta $e157
        lda $fd
        sta $e158
        lda $fe
        sta $e159
        lda $ff
        sta $e15a
        lda $e023
        clc
        adc $e0d9
        pha
        and #$07
        tay
        lda $e0dc
        adc #$00
        sta $ff
        pla
        lsr $ff
        ror
        lsr $ff
        ror
        lsr $ff
        ror
        clc
        adc $e024
        sty $d415
        sta $d416
        lda $e025
        sta $d417
        lda $e026
        sta $d418
        lda #$d4
        sta $fc
        ldx #$00
ll1:
        lda $e000
        and $e162,x
        beq l9

        lda $e165,x
        sta $fb
        lda $e00e,x
        clc
        adc $e051,x
        tay
        lda $e011,x
        adc $e054,x
        pha
        tya
        clc
        adc $e0cd,x
        ldy #$00
        sta ($fb),y
        pla
        adc $e0d0,x
        iny
        sta ($fb),y
        lda $e014,x
        clc
        adc $e069,x
        sta $ff
        lda $e017,x
        adc $e06c,x
        pha
        lda $ff
        clc
        adc $e0d3,x
        iny
        sta ($fb),y
        pla
        adc $e0d6,x
        iny
        sta ($fb),y
        lda $e01d,x
        iny
        iny
        sta ($fb),y
        lda $e020,x
        iny
        sta ($fb),y
l9:
        inx
        cpx #$03
        bne ll1

        ldy $e01a
        ldx $e01b
        lda $e01c
        sty $d404
        stx $d40b
        sta $d412
        ldx $e02d
        ldy $e02e
        stx $dc04
        sty $dc05
        lda $d41b
        sta $e0be
        lda $d41c
        sta $e0bf
        ldx #$00
ll3:
        lda $e000
        and $e162,x
        beq ll2

        stx $e02f
        jsr $e536
        lda $e000
        and #$78
        beq ll2
        jmp $e50c
ll2:
        inx
        cpx #$03
        bne ll3

        lda $e0c9
        bne ll4

        lda $e0ca
        ora $e0cb
        beq lll3

        lda $e0df
        bne ll6
lll1:
        lda $e0ca
        beq ll7
        clc
        adc $e0bd
        bcs ll8
        cmp $e0cc
        bcc ll9
        beq ll9
ll8:
        lda #$00
        sta $e0df
        lda $e0cb
        beq ll9
        inc $e0df
        lda $e0bd
        sbc $e0cb
        jmp ll9
ll6:
        lda $e0cb
        beq lll1

ll7:
        lda $e0bd
        sec
        sbc $e0cb
        bcs ll9

        lda #$00
        sta $e0df
        lda $e0ca
        bne ll9
        inc $e0df
ll5:
        bne lll2
ll4:
        dec $e0e0
        bne lll3
        lda $e0df
        bne lll4
        inc $e0df
        lda $e0cb
        bne lll5
        lda #$20
lll5:
        sta $e0e0
        lda #$00
        beq ll9
lll4:
        dec $e0df
        lda $e0ca
        bne lll6
        lda #$20
lll6:
        sta $e0e0
lll2:
        lda $e0cc
ll9:
        sta $e0bd
lll3:
        ldx #$00
loop7:
        lda $e0c3,x
        beq loop1
        lda #$00
        sta $ff
        ldy $e0c0,x
        lda $e0bd,y
        ldy $e0c6,x
        beq loop2
        bmi loop3
loop4:
        asl
        rol $ff
        dey
        bne loop4
        beq loop2
loop3:
        lsr
        iny
        bne loop3
loop2:
        ldy $e0c3,x
        dey
        bne loop5
        sta $e0cd,x
        lda $ff
        sta $e0d0,x
        jmp $e502
loop5:
        dey
        bne loop6
        sta $e0d3,x
        lda $ff
        sta $e0d6,x
        jmp $e502
loop6:
        sta $e0d9
        lda $ff
        sta $e0dc
loop1:
        inx
        cpx #$03
        bne loop7

        lda $e000
        and #$7f
        sta $e000
        lda $e156
        sta $fb
        lda $e157
        sta $fc
        lda $e158
        sta $fd
        lda $e159
        sta $fe
        lda $e15a
        sta $ff
        jmp ($e15d)
loop10:
        lda $e060,x
        bne loop8

        jmp $e69f
loop8:
        jmp $e5ba
        dec $e030,x
        bne loop9
        jmp $e6a0
loop9:
        lda $e036,x
        bmi loop10
        bne loop11
        lda $e03f,x
        beq loop12
        dec $e03f,x
        bne loop11
loop12:
        lda $e039,x
        cmp $e030,x
        bcc loop11
        lda $e01a,x
        and #$fe
        sta $e01a,x
loop11:
        lda $e042,x
        beq loop13
        asl
        lda $e00e,x
        bcs loop14
        adc $e045,x
        sta $e00e,x
        tay
        lda $e011,x
        adc $e048,x
        sta $e011,x
        pha
        tya
        cmp $e08d,x
        pla
        sbc $e090,x
        bcs loop15
        bcc loop16
loop14:
        sbc $e045,x
        sta $e00e,x
        lda $e011,x
        sbc $e048,x
        sta $e011,x
        lda $e08d,x
        cmp $e00e,x
        lda $e090,x
        sbc $e011,x
        bcc loop16
loop15:
        lda $e08d,x
        sta $e00e,x
        lda $e090,x
        sta $e011,x
        lda #$00
        sta $e042,x
loop16:
        lda $e060,x
        beq loop17
loop13:
        lda $e04b,x
        beq loop18
        ldy #$00
        dec $e04e,x
        bne loop20
        lda $e051,x
        ora $e054,x
        bne loop21
        lda $e05d,x
        sta $e057,x
        sta $e04e,x
        lda $e04b,x
        asl
        lda $e05a,x
        bcc loop22
        eor #$ff
        adc #$00
loop22:
        sta $e04b,x
        bne loop23
loop21:
        lda $e057,x
        sta $e04e,x
        tya
        sec
        sbc $e04b,x
        sta $e04b,x
loop20:
        cmp #$00
loop23:
        bpl loop24
        dey
loop24:
        clc
        adc $e051,x
        sta $e051,x
        tya
        adc $e054,x
        sta $e054,x
loop18:
        lda $e036,x
        bmi loop25
loop17:
        lda $e093,x
        beq loop25
        clc
        adc $e014,x
        sta $e014,x
        lda $e096,x
        adc $e017,x
        sta $e017,x
loop25:
        lda $e063,x
        beq loop26
        ldy #$00
        dec $e066,x
        bne loop27
        lda $e069,x
        ora $e06c,x
        bne loop28
        lda $e072,x
        sta $e06f,x
        sta $e066,x
        lda $e063,x
        asl
        lda $e075,x
        bcc loop29
        eor #$ff
        adc #$00
loop29:
        sta $e063,x
        bne loop30
loop28:
        lda $e06f,x
        sta $e066,x
        tya
        sec
        sbc $e063,x
        sta $e063,x
loop27:
        cmp #$00
loop30:
        bpl loop31
        dey
loop31:
        clc
        adc $e069,x
        sta $e069,x
        tya
        adc $e06c,x
        sta $e06c,x
loop26:
        lda $e036,x
        bpl loop31b
        jmp $e69f
loop31b:
        ldy #$00
        lda $e0a2,x
        beq loop32
        bpl loop33
        iny
loop33:
        clc
        adc $e023
        pha
        and #$07
        sta $e023
        pla
        ror
        lsr
        lsr
        clc
        adc $e1a6,y
        clc
        adc $e024
        sta $e024
loop32:
        rts
        lda $e0a8,x
        sta $fd
        lda $e0ab,x
        sta $fe
        bne loop34
loop35:
        rts
loop36:
        jsr $e898
loop34:
        lda $e000
        and $e162,x
        beq loop35
        ldy #$00
        lda ($fd),y
        sta $ff
        iny
        lda ($fd),y
        tay
        lda $fd
        clc
        adc #$02
        sta $fd
        sta $e0a8,x
        lda $fe
        adc #$00
        sta $fe
        sta $e0ab,x
        lda $ff
        and #$03
        bne loop36
        lda $e08d,x
        sta $e00e,x
        lda $e090,x
        sta $e011,x
        lda $ff
        sta $e005,x
        tya
        sta $e002,x
        and #$07
        tay
        lda $e167,y
        sta $e16f
        lda $e002,x
        and #$38
        lsr
        lsr
        lsr
        adc $e081,x
        sta $fd
        lda $e002,x
        and #$c0
        asl
        rol
        rol
        tay
        lda $e16f,y
        sta $fe
        lda $e002,x
        and #$07
        beq loop37
        tay
        lda $e172,y
        adc $fe
        clc
        adc $e084,x
        bpl loop38
        clc
        adc #$0c
        inc $fd
loop38:
        cmp #$0c
        bcc loop39
        sbc #$0c
        dec $fd
loop39:
        sta $fe
        tay
        lda $e186,y
        sta $ff
        lda $e17a,y
        ldy $fd
        dey
        bmi loop40
loop41:
        lsr $ff
        ror
        dey
        bpl loop41
loop40:
        clc
        adc $e087,x
        sta $e08d,x
        lda $ff
        adc $e08a,x
        sta $e090,x
        lda $e005,x
        bne loop42
        jmp $e6a0
loop42:
        lda $e045,x
        ora $e048,x
        beq loop43
        lda $e00e,x
        cmp $e08d,x
        lda $e011,x
        sbc $e090,x
        lda #$fe
        ror
        sta $e042,x
        bcc loop44
loop37:
        beq loop45
loop43:
        sta $e042,x
        lda $e08d,x
        sta $e00e,x
        lda $e090,x
        sta $e011,x
loop44:
        lda $e036,x
        asl
        bne loop45
        lda $e093,x
        beq loop46
        lda $e099,x
        sta $e014,x
        lda $e09c,x
        sta $e017,x
loop46:
        lda $e09f,x
        beq loop47
        ldy $fd
        clc
        adc $e192,y
        ldy $fe
        clc
        adc $e19a,y
        clc
        bcc loop48
loop47:
        lda $e0a2,x
        beq loop45
        lda $e0a5,x
loop48:
        sta $e024
        lda #$00
        sta $e023
loop45:
        lda $e03c,x
        sta $e03f,x
        lda $e005,x
        and #$40
        sta $e036,x
        lda $e005,x
        lsr
        lsr
        and #$07
        bne loop49
        lda $e005,x
        bmi loop50
        lda $e027
        and #$3c
        bne loop51
        lda $e027
        asl
        rol
        rol
        bne loop52
        lda #$04
loop52:
        jmp $e870
loop50:
        lda $e028
        beq loop51
        and #$3f
        bne loop51
        lda $e028
        asl
        rol
        rol
        bne loop53
loop51:
        lda #$10
        sta $e000
        rts
loop49:
        cmp #$01
        bne loop54
        lda $e005,x
        and #$20
        bne loop55
        lda $e029
        jmp $e870
loop55:
        lda $e02a,x
        jmp $e870
loop54:
        tay
        lda $e005,x
        and #$a0
        cmp #$80
        beq loop56
        sta $ff
        clc
        lda $e027
        bne loop57
        sec
loop57:
        dey
        dey
        beq loop58
loop60:
        ror
        bcs loop59
        dey
        bne loop60
loop58:
        ldy $ff
        sta $ff
        beq loop53
        lsr $ff
        bcs loop59
        beq loop61+1
        adc $ff
        bcs loop61+1
        iny
        bpl loop53
        lsr $ff
        bcs loop59
        adc $ff
        bcc loop53
        bcs loop61+1
loop56:
        lda $e028
        beq loop59
        dey
        dey
        beq loop53
loop62:
        lsr
        bcs loop59
        dey
        bne loop62
loop53:
        sta $e030,x
        lda $e01a,x
        and #$f6
        sta $e01a,x
        sec
        lda $e002,x
        and #$07
        bne loop63
        ror $e036,x
loop63:
        lda $e01a,x
        adc #$00
        sta $e01a,x
        rts
loop59:
        lda #$10
loop61:
        bit $18a9
        sta $e000
        rts
        tya
        pha
        lda $ff
        lsr
        bcc loop64
        jmp $ea42
loop64:
        lsr
        lsr
        bcs loop65
        lsr
        bcs loop66
        sta $e09c,x
        sta $e017,x
        pla
        sta $e099,x
        sta $e014,x
        rts
loop66:
        lsr
        bcc loop67
        ora #$f8
loop67:
        sta $e08a,x
        pla
        sta $e087,x
        rts
loop65:
        lsr
        bcs loop68
        jmp $e94a
loop68:
        lsr
        bcs loop69
        lsr
        bcs loop138
        bne loop70
        pla
        sta $e0a5,x
        sta $e024
        rts
loop70:
        pla
        sta $e03c,x
        rts
loop138:
        bne loop71
        pla
        sta $e07e,x
        cmp #$5b
        beq loop72
        tay
        lsr
        lsr
        lsr
        sec
        sbc #$0b
        clc
        adc $e084,x
        bmi loop73
        cmp #$0c
        bcc loop74
        sbc #$0c
        dec $e081,x
        jmp $e90b
loop73:
        cmp #$f5
        bcs loop74
        adc #$0c
        inc $e081,x
loop74:
        sta $e084,x
        tya
        and #$07
        sec
        sbc #$03
        clc
        adc $e081,x
        sta $e081,x
        rts
loop72:
        lda $e078,x
        sta $e081,x
        lda $e07b,x
        sta $e084,x
        rts
loop71:
        pla
        sta $e0c6,x
        rts
loop69:
        lsr
        bcs loop75
        sta $e00b,x
        pla
        sta $e008,x
        rts
loop75:
        lsr
        ror
        ror
        adc $e15b
        sta $e02d
        pla
        adc $e15c
        sta $e02e
        rts
        lsr
        bcc loop76
        jmp $e9d3
loop76:
        lsr
        bcs loop77
        lsr
        bcs loop78
        lsr
        bcs loop79
        pla
        sta $e027
        lsr
        lsr
        lsr
        tay
        lda $e1af,y
        sta $e028
        rts
loop79:
        pla
        sta $e05d,x
        rts
loop78:
        lsr
        bcs loop80
        pla
        sta $e001
        rts
loop80:
        pla
        beq loop81
        sta $e075,x
        ldy $e063,x
        bne loop82
        sta $e063,x
        lda #$01
        sta $e066,x
loop82:
        rts
loop81:
        sta $e063,x
        sta $e069,x
        sta $e06c,x
        rts
loop77:
        lsr
        bcs loop83
        lsr
        bcs loop84
        pla
        sta $e039,x
        rts
loop84:
        pla
        ldy #$00
        lsr
        bcc loop85
        iny
        clc
loop85:
        pha
        and #$07
        adc $e1ac,y
        sta $e078,x
        sta $e081,x
        pla
        lsr
        lsr
        lsr
        clc
        adc $e1ad,y
        sta $e07b,x
        sta $e084,x
        lda #$5b
        sta $e07e,x
        rts
loop83:
        lsr
        bcs loop86
        pla
        sta $e0a2,x
        rts
loop86:
        pla
        sta $e0cc
        rts
        lsr
        bcs loop87
        lsr
        bcs loop88
        lsr
        bcs loop89
        pla
        sta $e029
        rts
loop89:
        pla
        sta $e09f,x
        rts
loop88:
        lsr
        bcs loop90
        pla
        sta $e093,x
        ldy #$00
        asl
        bcc loop91
        dey
loop91:
        tya
        sta $e096,x
        rts
loop90:
        pla
        sta $e072,x
        rts
loop87:
        lsr
        bcs loop92
        lsr
        bcs loop93
        pla
        sta $e0b7,x
        lda $fd
        sta $e0b1,x
        lda $fe
        sta $e0b4,x
        lda $e033,x
        sta $e0ae,x
        rts
loop93:
        pla
        jmp ($e15f)
loop92:
        lsr
        bcs loop94
        pla
        bne loop95
        sta $e04b,x
        sta $e051,x
        sta $e054,x
        rts
loop95:
        sta $e05a,x
        ldy $e04b,x
        bne loop96

        sta $e04b,x
        lda #$01
        sta $e04e,x
loop96:
        rts
loop94:
        pla
        sta $e02a,x
        rts
        lsr
        bcc loop97
        sta $e048,x
        pla
        sta $e045,x
        rts
loop97:
        pla
        lsr
        bcs loop98
        lsr
        bcs loop99
        lsr
        bcs loop100
        lsr
        ldy #$f0
        bne loop101
loop100:
        asl
        asl
        asl
        asl
        ldy #$0f
loop101:
        sta $ff
        tya
        bcs loop102
        and $e01d,x
        ora $ff
        sta $e01d,x
        rts
loop102:
        and $e020,x
        ora $ff
        sta $e020,x
        rts
loop99:
        lsr
        bcs loop98b
        lsr
        bcs loop103
        sta $ff
        lda $e0ba,x
        cmp $e1a9,x
        beq loop104+1
        inc $e0ba,x
        tay
        lda $fd
        sta $e0e1,y
        lda $fe
        sta $e0f0,y
        lda $e033,x
        sta $e12f,y
        ldy $ff
        lda $e117,y
        beq loop105
        sta $fe
        lda $e0ff,y
        sta $fd
        lda $e13e,y
        sta $e033,x
        rts
loop98:
        bcs loop106
loop98b:
        lsr
        bcs loop107
        tay
        lda $fd
        sta $e0ff,y
        lda $fe
        sta $e117,y
        lda $e033,x
        sta $e13e,y
        lda $e0ba,x
        cmp $e1a9,x
        beq loop104+1
        inc $e0ba,x
        tay
        lda #$00
        sta $e0f0,y
        rts
loop105:
        lda #$30
loop104:
        bit $28a9
        sta $e000
        rts
loop103:
        asl
        asl
        asl
        asl
        eor $e025
        and #$f0
        eor $e025
        sta $e025
        rts
loop107:
        eor $e026
        and #$0f
        eor $e026
        sta $e026
        rts
loop106:
        lsr
        bcs loop108
        lsr
        bcs loop109
        sta $e0ca
        rts
loop109:
        sta $e0cb
        rts
loop108:
        lsr
        bcc loop110
        jmp $eba5
loop110:
        lsr
        tay
        beq loop111
        dey
        beq loop112
        dey
        beq loop113
        dey
        beq loop114
        dey
        beq loop115
        dey
        beq loop116
        dey
        beq loop117
        dey
        beq loop118
        and #$07
        ora #$10
        bcs loop111b
        jmp $eab7
loop111b:
        jmp $ea7f
loop111:
        ldy $e026
        bcs loop119
        iny
        tya
        and #$0f
        bne loop120
        rts
loop119:
        tya
        and #$0f
        beq loop121
        dey
loop120:
        sty $e026
loop121:
        rts
loop112:
        lda $e162,x
        eor #$ff
        and $e025
        bcc loop122
        ora $e162,x
loop122:
        sta $e025
        rts
loop113:
        lda $e01a,x
        and #$fb
        bcc loop123
        ora #$04
        bcs loop123
loop114:
        lda $e01a,x
        and #$fd
        bcc loop123
        ora #$02
        bcs loop123
loop115:
        lda $e025
        and #$f7
        bcc loop124
        ora #$08
loop124:
        sta $e025
        rts
loop116:
        lda $e026
        and #$7f
        bcc loop125
        ora #$80
loop125:
        sta $e026
        rts
loop117:
        tya
        sta $e0bd
        sta $e0df
        iny
        sty $e0e0
        rol
        sta $e0c9
        rts
loop118:
        tya
        rol
        sta $e060,x
        rts
        lsr
        bcs loop126
        lsr
        bcs loop127
        bne loop128
        lda #$08
loop128:
        asl
        asl
        asl
        asl
        eor $e01a,x
        and #$f0
        eor $e01a,x
loop123:
        sta $e01a,x
        rts
loop127:
        asl
        asl
        asl
        asl
        eor $e026
        and #$70
        eor $e026
        sta $e026
        rts
loop126:
        lsr
        bcc loop129
        sta $e0c0,x
        rts
loop129:
        tay
        beq loop130
        dey
        beq loop131
        dey
        beq loop139
        and #$03
        sta $e0c3,x
        lda #$00
        sta $e0cd,x
        sta $e0d0,x
        sta $e0d3,x
        sta $e0d6,x
        sta $e0d9
        sta $e0dc
        rts
loop130:
        lda $e0b7,x
        beq loop132
        dec $e0b7,x
        beq loop133
loop132:
        lda $e033,x
        cmp $e0ae,x
        bne loop134
        lda $e0b1,x
        sta $fd
        lda $e0b4,x
        sta $fe
loop133:
        rts
loop134:
        lda #$38
        sta $e000
        rts
loop131:
        lda $e0ba,x
        cmp $e1a8,x
        beq loop135
        dec $e0ba,x
        tay
        dey
        lda $e0f0,y
        beq loop136
        sta $fe
        lda $e0e1,y
        sta $fd
        lda $e12f,y
        sta $e033,x
loop136:
        rts
loop135:
        lda #$20
        sta $e000
        rts
loop139:
        lda $e000
        eor $e162,x
        sta $e000
        lda #$01
        sta $e030,x
        rts
        lda $e000
        and #$07
        sta $ec81
        bne loop137
        jsr $e2e9
loop137:
        rts
        brk
init:
        ldx #$51
        ldy #$ec
        stx $e15d
        sty $e15e
        jsr $e1cf
data_low:
        ldx #$00
data_high:
        ldy #$09
        jsr $e200
        lda #$07
        sta $e000
        sta $ec81
loop138b:
        rts
        brk
        brk
        brk
start:
        lda #$00
        and #$ff
        beq loop138b

        jmp $e329
        lda #$07
        sta $e000
        rts
