// Source generated by DCC6502 version v2.0
// For more info about DCC6502, see https://github.com/tcarmelveilleux/dcc6502
// FILENAME: ../../Documents/sidplayer2.prg, File Size: 3229, ORG: $F000
//---------------------------------------------------------------------------
.pc = $F000
.fill $015f,0

.byte $61, $F1, $60, $01, $02, $04, $00, $07
.byte $0E, $02, $02, $FE, $02, $02, $FE, $FE
.byte $00, $01, $00, $FF, $00, $02, $04, $05
.byte $07, $09, $0B, $1E, $18, $8B, $7E, $FA
.byte $06, $AC, $F3, $E6, $8F, $F8, $2E, $86
.byte $8E, $96, $9F, $A8, $B3, $BD, $C8, $D4
.byte $E1, $EE, $FD, $8C, $78, $64, $50, $3C
.byte $28, $14, $00, $00, $02, $03, $05, $07
.byte $08, $0A, $0C, $0D, $0F, $11, $12, $00
.byte $E0, $00, $05, $0A, $0F, $F9, $00, $F5
.byte $00, $00, $00, $10, $00, $00, $20, $00
.byte $00, $30, $00, $00, $40, $00, $00, $50
.byte $00, $00, $60, $00, $00, $70, $00, $00
.byte $80, $00, $00, $90, $00, $00


        ldy #$00
        lda #$00
        sta $f000
        ldx #$95
        ldy #$42
        lda $02a6
        beq loop1

        ldx #$25
        ldy #$40
loop1:
        stx $f15b
        sty $f15c
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        rts
        lda #$00
        sta $f000
        stx $61
        sty $62
        ldy #$bc
loop2:
        sta $f000,y
        dey
        bne loop2
        ldy #$72
loop3:
        sta $f0bc,y
        dey
        bne loop3
        sta $d515
        sta $d516
        lda #$08
        sta $f025
        sta $d517
        sta $f026
        sta $d518
        lda #$90
        sta $f027
        lda #$60
        sta $f028
        lda #$0c
        sta $f029
        lda $f15b
        sta $f02d
        lda $f15c
        sta $f02e
        lda #$ff
        sta $f0cc
        lda #$d5
        sta $64
        ldx #$02
loop4:
        lda #$ff
        sta $f00b,x
        lda #$01
        sta $f030,x
        sta $f02a,x
        txa
        sta $f033,x
        sta $f0ae,x
        lda #$04
        sta $f039,x
        lda $f1a8,x
        sta $f0ba,x
        lda #$5b
        sta $f07e,x
        lda $f165,x
        sta $63
        lda #$00
        tay
        sta ($63),y
        iny
        sta ($63),y
        iny
        sta ($63),y
        lda #$08
        sta $f017,x
        sta $f09c,x
        iny
        sta ($63),y
        iny
        sta ($63),y
        lda #$40
        sta $f01a,x
        sta ($63),y
        lda #$20
        sta $f01d,x
        iny
        sta ($63),y
        lda #$f5
        sta $f020,x
        iny
        sta ($63),y
        dex
        bpl loop4
        txa
        ldx #$17
loop5:
        sta $f13e,x
        dex
        bpl loop5
        lda $61
        clc
        adc #$06
        sta $63
        lda #$00
        tax
        tay
        adc $62
loop6:
        sta $64
        sta $f0ab,x
        sta $f0b4,x
        lda $63
        sta $f0a8,x
        sta $f0b1,x
        clc
        adc ($61),y
        sta $63
        lda $64
        iny
        adc ($61),y
        iny
        inx
        cpx #$03
        bne loop6
        ldx $63
        tay
        rts
        lda #$00
        sta $d504
        sta $d50b
        sta $d512
        sta $d501
        sta $d508
        sta $d50f
        lda #$08
        sta $d517
        lda $f15b
        sta $dc04
        lda $f15c
        sta $dc05
        rts
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        rts
loop7:
        lda #$08
        sta $f000
loop8:
        jmp ($f15d)
        nop
        nop
        nop
        lda $f000
        bmi loop7
        ora #$80
        tay
        and #$07
        beq loop8
        cld
        sty $f000
        nop
        lda $fb
        sta $f156
        lda $fc
        sta $f157
        lda $fd
        sta $f158
        lda $fe
        sta $f159
        lda $ff
        sta $f15a
        lda $f023
        clc
        adc $f0d9
        pha
        and #$07
        tay
        lda $f0dc
        adc #$00
        sta $ff
        pla
        lsr $ff
        ror
        lsr $ff
        ror
        lsr $ff
        ror
        clc
        adc $f024
        sty $d515
        sta $d516
        lda $f025
        sta $d517
        lda $f026
        sta $d518
        lda #$d5
        sta $fc
        ldx #$00
loop10:
        lda $f000
        and $f162,x
        beq loop9
        lda $f165,x
        sta $fb
        lda $f00e,x
        clc
        adc $f051,x
        tay
        lda $f011,x
        adc $f054,x
        pha
        tya
        clc
        adc $f0cd,x
        ldy #$00
        sta ($fb),y
        pla
        adc $f0d0,x
        iny
        sta ($fb),y
        lda $f014,x
        clc
        adc $f069,x
        sta $ff
        lda $f017,x
        adc $f06c,x
        pha
        lda $ff
        clc
        adc $f0d3,x
        iny
        sta ($fb),y
        pla
        adc $f0d6,x
        iny
        sta ($fb),y
        lda $f01d,x
        iny
        iny
        sta ($fb),y
        lda $f020,x
        iny
        sta ($fb),y
loop9:
        inx
        cpx #$03
        bne loop10
        ldy $f01a
        ldx $f01b
        lda $f01c
        sty $d504
        stx $d50b
        sta $d512
        ldx $f02d
        ldy $f02e
        stx $dc04
        sty $dc05
        lda $d51b
        sta $f0be
        lda $d51c
        sta $f0bf
        ldx #$00
loop12:
        lda $f000
        and $f162,x
        beq loop11
        stx $f02f
        jsr $f536
        lda $f000
        and #$78
        beq loop11
        jmp $f50c
loop11:
        inx
        cpx #$03
        bne loop12
        lda $f0c9
        bne loop13
        lda $f0ca
        ora $f0cb
        beq loop14
        lda $f0df
        bne loop15
loop19:
        lda $f0ca
        beq loop16
        clc
        adc $f0bd
        bcs loop17
        cmp $f0cc
        bcc loop18
        beq loop18
loop17:
        lda #$00
        sta $f0df
        lda $f0cb
        beq loop18
        inc $f0df
        lda $f0bd
        sbc $f0cb
        jmp $f4b4
loop15:
        lda $f0cb
        beq loop19
loop16:
        lda $f0bd
        sec
        sbc $f0cb
        bcs loop18
        lda #$00
        sta $f0df
        lda $f0ca
        bne loop18
        inc $f0df
        bne loop20
loop13:
        dec $f0e0
        bne loop14
        lda $f0df
        bne loop21
        inc $f0df
        lda $f0cb
        bne loop22
        lda #$20
loop22:
        sta $f0e0
        lda #$00
        beq loop18
loop21:
        dec $f0df
        lda $f0ca
        bne loop23
        lda #$20
loop23:
        sta $f0e0
loop20:
        lda $f0cc
loop18:
        sta $f0bd
loop14:
        ldx #$00
loop30:
        lda $f0c3,x
        beq loop24
        lda #$00
        sta $ff
        ldy $f0c0,x
        lda $f0bd,y
        ldy $f0c6,x
        beq loop25
        bmi loop26
loop27:
        asl
        rol $ff
        dey
        bne loop27
        beq loop25
loop26:
        lsr
        iny
        bne loop26
loop25:
        ldy $f0c3,x
        dey
        bne loop28
        sta $f0cd,x
        lda $ff
        sta $f0d0,x
        jmp $f502
loop28:
        dey
        bne loop29
        sta $f0d3,x
        lda $ff
        sta $f0d6,x
        jmp $f502
loop29:
        sta $f0d9
        lda $ff
        sta $f0dc
loop24:
        inx
        cpx #$03
        bne loop30
        lda $f000
        and #$7f
        sta $f000
        lda $f156
        sta $fb
        lda $f157
        sta $fc
        lda $f158
        sta $fd
        lda $f159
        sta $fe
        lda $f15a
        sta $ff
        jmp ($f15d)
loop33:
        lda $f060,x
        bne loop31
        jmp $f69f
loop31:
        jmp $f5ba
        dec $f030,x
        bne loop32
        jmp $f6a0
loop32:
        lda $f036,x
        bmi loop33
        bne loop34
        lda $f03f,x
        beq loop35
        dec $f03f,x
        bne loop34
loop35:
        lda $f039,x
        cmp $f030,x
        bcc loop34
        lda $f01a,x
        and #$fe
        sta $f01a,x
loop34:
        lda $f042,x
        beq loop36
        asl
        lda $f00e,x
        bcs loop37
        adc $f045,x
        sta $f00e,x
        tay
        lda $f011,x
        adc $f048,x
        sta $f011,x
        pha
        tya
        cmp $f08d,x
        pla
        sbc $f090,x
        bcs loop38
        bcc loop39
loop37:
        sbc $f045,x
        sta $f00e,x
        lda $f011,x
        sbc $f048,x
        sta $f011,x
        lda $f08d,x
        cmp $f00e,x
        lda $f090,x
        sbc $f011,x
        bcc loop39
loop38:
        lda $f08d,x
        sta $f00e,x
        lda $f090,x
        sta $f011,x
        lda #$00
        sta $f042,x
loop39:
        lda $f060,x
        beq loop40
loop36:
        lda $f04b,x
        beq loop41
        ldy #$00
        dec $f04e,x
        bne loop42
        lda $f051,x
        ora $f054,x
        bne loop43
        lda $f05d,x
        sta $f057,x
        sta $f04e,x
        lda $f04b,x
        asl
        lda $f05a,x
        bcc loop44
        eor #$ff
        adc #$00
loop44:
        sta $f04b,x
        bne loop45
loop43:
        lda $f057,x
        sta $f04e,x
        tya
        sec
        sbc $f04b,x
        sta $f04b,x
loop42:
        cmp #$00
loop45:
        bpl loop46
        dey
loop46:
        clc
        adc $f051,x
        sta $f051,x
        tya
        adc $f054,x
        sta $f054,x
loop41:
        lda $f036,x
        bmi loop47
loop40:
        lda $f093,x
        beq loop47
        clc
        adc $f014,x
        sta $f014,x
        lda $f096,x
        adc $f017,x
        sta $f017,x
loop47:
        lda $f063,x
        beq loop48
        ldy #$00
        dec $f066,x
        bne loop49
        lda $f069,x
        ora $f06c,x
        bne loop60
        lda $f072,x
        sta $f06f,x
        sta $f066,x
        lda $f063,x
        asl
        lda $f075,x
        bcc loop61
        eor #$ff
        adc #$00
loop61:
        sta $f063,x
        bne loop62
loop60:
        lda $f06f,x
        sta $f066,x
        tya
        sec
        sbc $f063,x
        sta $f063,x
loop49:
        cmp #$00
loop62:
        bpl loop63
        dey
loop63:
        clc
        adc $f069,x
        sta $f069,x
        tya
        adc $f06c,x
        sta $f06c,x
loop48:
        lda $f036,x
        bpl loop64
        jmp $f69f
loop64:
        ldy #$00
        lda $f0a2,x
        beq loop65
        bpl loop66
        iny
loop66:
        clc
        adc $f023
        pha
        and #$07
        sta $f023
        pla
        ror
        lsr
        lsr
        clc
        adc $f1a6,y
        clc
        adc $f024
        sta $f024
loop65:
        rts
        lda $f0a8,x
        sta $fd
        lda $f0ab,x
        sta $fe
        bne loop67
loop68:
        rts
loop69:
        jsr $f898
loop67:
        lda $f000
        and $f162,x
        beq loop68
        ldy #$00
        lda ($fd),y
        sta $ff
        iny
        lda ($fd),y
        tay
        lda $fd
        clc
        adc #$02
        sta $fd
        sta $f0a8,x
        lda $fe
        adc #$00
        sta $fe
        sta $f0ab,x
        lda $ff
        and #$03
        bne loop69
        lda $f08d,x
        sta $f00e,x
        lda $f090,x
        sta $f011,x
        lda $ff
        sta $f005,x
        tya
        sta $f002,x
        and #$07
        tay
        lda $f167,y
        sta $f16f
        lda $f002,x
        and #$38
        lsr
        lsr
        lsr
        adc $f081,x
        sta $fd
        lda $f002,x
        and #$c0
        asl
        rol
        rol
        tay
        lda $f16f,y
        sta $fe
        lda $f002,x
        and #$07
        beq loop70
        tay
        lda $f172,y
        adc $fe
        clc
        adc $f084,x
        bpl loop71
        clc
        adc #$0c
        inc $fd
loop71:
        cmp #$0c
        bcc loop72

        sbc #$0c
        dec $fd
loop72:
        sta $fe
        tay
        lda $f186,y
        sta $ff
        lda $f17a,y
        ldy $fd
        dey
        bmi loop73
loop74:
        lsr $ff
        ror
        dey
        bpl loop74
loop73:
        clc
        adc $f087,x
        sta $f08d,x
        lda $ff
        adc $f08a,x
        sta $f090,x
        lda $f005,x
        bne loop75
        jmp $f6a0
loop75:
        lda $f045,x
        ora $f048,x
        beq loop76
        lda $f00e,x
        cmp $f08d,x
        lda $f011,x
        sbc $f090,x
        lda #$fe
        ror
        sta $f042,x
        bcc loop77
loop70:
        beq loop78
loop76:
        sta $f042,x
        lda $f08d,x
        sta $f00e,x
        lda $f090,x
        sta $f011,x
loop77:
        lda $f036,x
        asl
        bne loop78
        lda $f093,x
        beq loop79
        lda $f099,x
        sta $f014,x
        lda $f09c,x
        sta $f017,x
loop79:
        lda $f09f,x
        beq loop80
        ldy $fd
        clc
        adc $f192,y
        ldy $fe
        clc
        adc $f19a,y
        clc
        bcc loop81
loop80:
        lda $f0a2,x
        beq loop78
        lda $f0a5,x
loop81:
        sta $f024
        lda #$00
        sta $f023
loop78:
        lda $f03c,x
        sta $f03f,x
        lda $f005,x
        and #$40
        sta $f036,x
        lda $f005,x
        lsr
        lsr
        and #$07
        bne loop82
        lda $f005,x
        bmi loop83
        lda $f027
        and #$3c
        bne loop84
        lda $f027
        asl
        rol
        rol
        bne loop85
        lda #$04
loop85:
        jmp $f870
loop83:
        lda $f028
        beq loop84
        and #$3f
        bne loop84
        lda $f028
        asl
        rol
        rol
        bne loop86
loop84:
        lda #$10
        sta $f000
        rts
loop82:
        cmp #$01
        bne loop87
        lda $f005,x
        and #$20
        bne loop88
        lda $f029
        jmp $f870
loop88:
        lda $f02a,x
        jmp $f870
loop87:
        tay
        lda $f005,x
        and #$a0
        cmp #$80
        beq loop89
        sta $ff
        clc
        lda $f027
        bne loop90
        sec
loop90:
        dey
        dey
        beq loop91
loop93:
        ror
        bcs loop92
        dey
        bne loop93
loop91:
        ldy $ff
        sta $ff
        beq loop86
        lsr $ff
        bcs loop92
        beq $f892
        adc $ff
        bcs loop94+1
        iny
        bpl loop86
        lsr $ff
        bcs loop92
        adc $ff
        bcc loop86
        bcs loop94+1
loop89:
        lda $f028
        beq loop92
        dey
        dey
        beq loop86
loop95:
        lsr
        bcs loop92
        dey
        bne loop95
loop86:
        sta $f030,x
        lda $f01a,x
        and #$f6
        sta $f01a,x
        sec
        lda $f002,x
        and #$07
        bne loop96
        ror $f036,x
loop96:
        lda $f01a,x
        adc #$00
        sta $f01a,x
        rts
loop92:
        lda #$10
loop94:
        bit $18a9
        sta $f000
        rts
        tya
        pha
        lda $ff
        lsr
        bcc loop97
        jmp $fa42
loop97:
        lsr
        lsr
        bcs loop98
        lsr
        bcs loop99
        sta $f09c,x
        sta $f017,x
        pla
        sta $f099,x
        sta $f014,x
        rts
loop99:
        lsr
        bcc loop100
        ora #$f8
loop100:
        sta $f08a,x
        pla
        sta $f087,x
        rts
loop98:
        lsr
        bcs loop101
        jmp $f94a
loop101:
        lsr
        bcs loop102
        lsr
        bcs loop103
        bne loop104
        pla
        sta $f0a5,x
        sta $f024
        rts
loop104:
        pla
        sta $f03c,x
        rts
loop103:
        bne loop105
        pla
        sta $f07e,x
        cmp #$5b
        beq loop106
        tay
        lsr
        lsr
        lsr
        sec
        sbc #$0b
        clc
        adc $f084,x
        bmi loop107
        cmp #$0c
        bcc loop108

        sbc #$0c
        dec $f081,x
        jmp $f90b
loop107:
        cmp #$f5
        bcs loop108
        adc #$0c
        inc $f081,x
loop108:
        sta $f084,x
        tya
        and #$07
        sec
        sbc #$03
        clc
        adc $f081,x
        sta $f081,x
        rts
loop106:
        lda $f078,x
        sta $f081,x
        lda $f07b,x
        sta $f084,x
        rts
loop105:
        pla
        sta $f0c6,x
        rts
loop102:
        lsr
        bcs loop109
        sta $f00b,x
        pla
        sta $f008,x
        rts
loop109:
        lsr
        ror
        ror
        adc $f15b
        sta $f02d
        pla
        adc $f15c
        sta $f02e
        rts
        lsr
        bcc loop110
        jmp $f9d3
loop110:
        lsr
        bcs loop111
        lsr
        bcs loop112
        lsr
        bcs loop113
        pla
        sta $f027
        lsr
        lsr
        lsr
        tay
        lda $f1af,y
        sta $f028
        rts
loop113:
        pla
        sta $f05d,x
        rts
loop112:
        lsr
        bcs loop112b
        pla
        sta $f001
        rts
loop112b:
        pla
        beq loop114
        sta $f075,x
        ldy $f063,x
        bne loop115
        sta $f063,x
        lda #$01
        sta $f066,x
loop115:
        rts
loop114:
        sta $f063,x
        sta $f069,x
        sta $f06c,x
        rts
loop111:
        lsr
        bcs loop116b
        lsr
        bcs loop117
        pla
        sta $f039,x
        rts
loop117:
        pla
        ldy #$00
        lsr
        bcc loop118
        iny
        clc
loop118:
        pha
        and #$07
        adc $f1ac,y
        sta $f078,x
        sta $f081,x
        pla
        lsr
        lsr
        lsr
        clc
        adc $f1ad,y
        sta $f07b,x
        sta $f084,x
        lda #$5b
        sta $f07e,x
        rts
loop116b:
        lsr
        bcs loop119
        pla
        sta $f0a2,x
        rts
loop119:
        pla
        sta $f0cc
        rts
        lsr
        bcs loop112c
        lsr
        bcs loop113b
        lsr
        bcs loop114b
        pla
        sta $f029
        rts
loop114b:
        pla
        sta $f09f,x
        rts
loop113b:
        lsr
        bcs loop115b

        pla
        sta $f093,x
        ldy #$00
        asl
        bcc loop116
        dey
loop116:
        tya
        sta $f096,x
        rts
loop115b:
        pla
        sta $f072,x
        rts
loop112c:
        lsr
        bcs loop117b
        lsr
        bcs loop118b
        pla
        sta $f0b7,x
        lda $fd
        sta $f0b1,x
        lda $fe
        sta $f0b4,x
        lda $f033,x
        sta $f0ae,x
        rts
loop118b:
        pla
        jmp ($f15f)
loop117b:
        lsr
        bcs loop119b
        pla
        bne loop120
        sta $f04b,x
        sta $f051,x
        sta $f054,x
        rts
loop120:
        sta $f05a,x
        ldy $f04b,x
        bne loop121
        sta $f04b,x
        lda #$01
        sta $f04e,x
loop121:
        rts
loop119b:
        pla
        sta $f02a,x
        rts
        lsr
        bcc loop122
        sta $f048,x
        pla
        sta $f045,x
        rts
loop122:
        pla
        lsr
        bcs loop123
        lsr
        bcs loop124
        lsr
        bcs loop125
        lsr
        ldy #$f0
        bne loop126
loop125:
        asl
        asl
        asl
        asl
        ldy #$0f
loop126:
        sta $ff
        tya
        bcs loop127
        and $f01d,x
        ora $ff
        sta $f01d,x
        rts
loop127:
        and $f020,x
        ora $ff
        sta $f020,x
        rts
loop124:
        lsr
        bcs loop127c
        lsr
        bcs loop127b
        sta $ff
        lda $f0ba,x
loop126b:
        cmp $f1a9,x
        beq loop128+1
        inc $f0ba,x
        tay
        lda $fd
        sta $f0e1,y
        lda $fe
        sta $f0f0,y
        lda $f033,x
        sta $f12f,y
        ldy $ff
        lda $f117,y
        beq loop129
        sta $fe
        lda $f0ff,y
        sta $fd
        lda $f13e,y
        sta $f033,x
        rts
loop123:
        bcs loop130
loop127c:
        lsr
        bcs loop131

        tay
        lda $fd
        sta $f0ff,y
        lda $fe
        sta $f117,y
        lda $f033,x
        sta $f13e,y
        lda $f0ba,x
        cmp $f1a9,x
        beq loop128+1
        inc $f0ba,x
        tay
        lda #$00
        sta $f0f0,y
        rts
loop129:
        lda #$30
loop128:
        bit $28a9
        sta $f000
        rts
loop127b:
        asl
        asl
        asl
        asl
        eor $f025
        and #$f0
        eor $f025
        sta $f025
        rts
loop131:
        eor $f026
        and #$0f
        eor $f026
        sta $f026
        rts
loop130:
        lsr
        bcs loop132
        lsr
        bcs loop133
        sta $f0ca
        rts
loop133:
        sta $f0cb
        rts
loop132:
        lsr
        bcc loop134
        jmp $fba5
loop134:
        lsr
        tay
        beq loop135
        dey
        beq loop136
        dey
        beq loop137
        dey
        beq loop138
        dey
        beq loop139
        dey
        beq loop140
        dey
        beq loop141
        dey
        beq loop142
        and #$07
        ora #$10
        bcs loop143
        jmp $fab7
loop143:
        jmp $fa7f
loop135:
        ldy $f026
        bcs loop144
        iny
        tya
        and #$0f
        bne loop145
        rts
loop144:
        tya
        and #$0f
        beq loop146
        dey
loop145:
        sty $f026
loop146:
        rts
loop136:
        lda $f162,x
        eor #$ff
        and $f025
        bcc loop147
        ora $f162,x
loop147:
        sta $f025
        rts
loop137:
        lda $f01a,x
        and #$fb
        bcc loop148
        ora #$04
        bcs loop148
loop138:
        lda $f01a,x
        and #$fd
        bcc loop148
        ora #$02
        bcs loop148
loop139:
        lda $f025
        and #$f7
        bcc loop149
        ora #$08
loop149:
        sta $f025
        rts
loop140:
        lda $f026
        and #$7f
        bcc loop150
        ora #$80
loop150:
        sta $f026
        rts
loop141:
        tya
        sta $f0bd
        sta $f0df
        iny
        sty $f0e0
        rol
        sta $f0c9
        rts
loop142:
        tya
        rol
        sta $f060,x
        rts
        lsr
        bcs loop151
        lsr
        bcs loop152
        bne loop153
        lda #$08
loop153:
        asl
        asl
        asl
        asl
        eor $f01a,x
        and #$f0
        eor $f01a,x
loop148:
        sta $f01a,x
        rts
loop152:
        asl
        asl
        asl
        asl
        eor $f026
        and #$70
        eor $f026
        sta $f026
        rts
loop151:
        lsr
        bcc loop154
        sta $f0c0,x
        rts
loop154:
        tay
        beq loop155
        dey
        beq loop156
        dey
        beq loop157
        and #$03
        sta $f0c3,x
        lda #$00
        sta $f0cd,x
        sta $f0d0,x
        sta $f0d3,x
        sta $f0d6,x
        sta $f0d9
        sta $f0dc
        rts
loop155:
        lda $f0b7,x
        beq loop158
        dec $f0b7,x
        beq loop159
loop158:
        lda $f033,x
        cmp $f0ae,x
        bne loop160
        lda $f0b1,x
        sta $fd
        lda $f0b4,x
        sta $fe
loop159:
        rts
loop160:
        lda #$38
        sta $f000
        rts
loop156:
        lda $f0ba,x
        cmp $f1a8,x
        beq loop161
        dec $f0ba,x
        tay
        dey
        lda $f0f0,y
        beq loop162
        sta $fe
        lda $f0e1,y
        sta $fd
        lda $f12f,y
        sta $f033,x
loop162:
        rts
loop161:
        lda #$20
        sta $f000
        rts
loop157:
        lda $f000
        eor $f162,x
        sta $f000
        lda #$01
        sta $f030,x
        rts
        lda $f000
        and #$07
        sta $fc81
        bne loop163
        jsr $f2e9
loop163:
        rts
        brk
        ldx #$51
        ldy #$fc
        stx $f15d
        sty $f15e
        jsr $f1cf
data_low:
        ldx #$00
data_high:
        ldy #$09
        jsr $f200
        lda #$07
        sta $f000
        sta $fc81
loop164:
        rts
        brk
        brk
        brk
        lda #$00
        and #$ff
        beq loop164
        jmp $f329
        lda #$07
        sta $f000
        rts
        brk
init:
        jsr $ec60
        jmp $fc60
start:
        jsr $ec80
        jmp $fc80
