/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hardsid_HardSID */

#ifndef _Included_hardsid_HardSID
#define _Included_hardsid_HardSID
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
