== SIDBlaster

The purpose of the SIDBlaster library is to access your SIDBlaster device using your own software.
This guide is for you to create and/or use that library.

=== Developer Instructions

This section is for developers in the need of creating the SIDBlaster library.
Reason can be, that you want to create your own project using the driver or you want to make changes.

The sources of the project are platform independent and compiles at least on Windows, Linux and MacOSX.

==== Creating the SIDBlaster library on MacOSX

*Pre-conditions*

Please choose a MacOSX machine which should use the library as a minimum requirement.
The library itself uses GLIBC on the machine which is downward compatible but not upward compatible.
I used MacOSX El Capitan as the build platform, but you can use any other MacOSX.
I expect the library cannot be used on older platforms than the build platform.

Mac OSX required a software called brew to install some tools required to compile the library.
This is namely the make tool itself and the compilers to build the lib.
It also created the required directories where the library will be installed to.

Please get installation instructions for brew from here:
https://treehouse.github.io/installation-guides/mac/homebrew

It seems the installer is called from the command line.
Therefore open a terminal and type-in the following instruction:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

The installer points out, that it wants to install the Xcode developer tools as well.
In fact it says: "The xcode-select command requires the command line developer tools. Would you like to install the tools now?"

It will install it automatically from the Apple store, unless it fails, because it can't actually find it for your computer.
Apple decides which updates you get on your MacOSX and there is a good chance, that
you cannot install it at that point,
so what do we do now?
We must install Xcode developer tools manually from the Apple developer portal and repeat the installation of brew.

Therefore go to the apple developer portal for manual download, but keep in mind you will need an account to enter it.
The direct download site to download Xcode developer tools is:
https://developer.apple.com/download/all/?q=xcode

Please select the following or a similar version suitable for your platform. On MacOSX Catalina, the following is compatible:
"Command Line Tools for Xcode 11.5 GM seed"

Click on Details and then click install.

After installation repeat installation command of brew (ruby ...)

at the end we need the cmake tool and we can install it using the freshly installed brew at the command line:
"brew install cmake"

To verify, that all requirements of this section are fullfilled,
you can call "make" and "cmake" on the command line (it must be found) and the directories: "/usr/local/lib" and "/usr/local/include" must exist.

*Installing the required ftd2xx library*

SIDBlaster library requires the ftd2xx library as a pre-condition. It must be there at compile time and
it will be loaded at runtime during the load process of the SIDBlaster library as well.
Therefore it must be installed on the machine where you want to use the SIDBlaster library, first.

Install ftd2xx drivers from here:
https://ftdichip.com

Please click on "Drivers"/"D2XX Drivers"
and in the section "Mac OSX 10.4 or later" click "1.4.24"
to install "D2XX1.4.24.dmg".
The installer is just a virtual file system which opens in the MacOSXs finder.

Now you must copy folder "release" to "Downloads" directory.

For the next steps you will need a terminal, please replace <name> by your username.

[source,subs="attributes+"]
----
cd /Users/<name>/Downloads/release/build
cp libftd2xx.1.4.24.dylib /usr/local/lib	 # <1>
cd ..
cp ftd2xx.h /usr/local/include				 # <2>
cd /usr/local/lib
ln -s libftd2xx.1.4.24.dylib libftd2xx.dylib # <3>
chmod 755 libftd2xx.1.4.24.dylib
chmod 755 libftd2xx.dylib
cd ../include
chmod 755 ftd2xx.h
----
<1> Copies the library to the runtime library search paths.
<2> Optional: Copies the header in case you want to compile your own project with ftd2xx library.
<3> Create a link to point the f2d2xx library to that exact version you installed.

The docs on the web-site points out, that a helper might be needed to use the library on your MacOSX,
therefore you should install D2XXHelper just in case.
Therefore, download D2XXHelper and call this installer.

For the sake of security reasons MacOSX blocks unknown libraries by reporting "System Extension blocked",
therefore we must give proper permission.
Therefore, open "Security and Privacy Settings" from the system settings dialog.
Unlock Settings with your password to be able to change one of these settings.
Now, click allow for the library mentioned here, that was blocked before.
Please restart D2XXHelper installation to end with success, now.

If you have trouble to complete the installation you can turn off security control completely, but i do not recommend that.

After typing
"spctl --master-disable"
you can choose to "Install apps downloaded from anywhere" right in the "Security and Privacy Settings".

*Creating/Installing the SIDlaster library*

Finally we are ready to download/compile/install the SIDBlaster library.

Please go to the following site to download SIDBlaster sources:
https://github.com/kenchis/SIDBlasterUSB_HardSID-emulation-driver

You *MUST* choose the apple branch to get the right sources to compile on your MacOSX.

Click on "Code" combobox
Click on "download ZIP"

After download extract it to the Downloads folder and open a terminal.

[source,subs="attributes+"]
----
cd /Users/<name>/Downloads/SIDBlasterUSB_HardSID-emulation-driver-apple
mkdir build
cd build
cmake ..			 # <1>
make				 # <2>
ls libhardsid.dylib	 # <3>
----
<1> Creates the makefiles in the build directory
<2> Compiles all the sources
<3> This last command verifies you have the SIDBlaster library created.

As a last step you can use that library inside of your project.
For JSIDPlay2 for instance you have to put it inside the main JAR (jsidplay2-4.3.jar)
in the sub-folder "src/main/resources/darwin"

=== User Instructions

*Use JSIDPlay2 with SIDBlaster on MacOSX*

JSIDPlay2 requires Java, therefore install java first.
I recommend to install it from the folowing site:
https://adoptopenjdk.net

Choose "OpenJDT11" and "Hotspot"

Then download and install it on your machine.

You can verify this ba opening the command line and type
"java -version"

Now you can install JSIDPlay2 from my web-site and extract it to the Downloads folder.

[source,subs="attributes+"]
----
cd /Users/<name>/Downloads/jsidplay2-4.3-java11-mac
chmod +x "JSIDPlay2 (Java11).sh"
"./JSIDPlay2 (Java11).sh"			 # <1>
----
<1> Before you launch JSIDPlay2 you must be sure, that you connected your SIDBlaster device with your machine.

*Note:* hot-plugging SIDBlaster devices is not supported. Therefore everytime you connect a device, you must restart JSIDPlay2, unfortunately.

Inside JSIDPlay2 on your tool bar you can now change from Emulation to SIDBlaster

This will again most likely raise a security alert.
Therefore, open "Security and Privacy Settings" from the system settings dialog.
Unlock Settings with your password to be able to change one of these settings.
Now, click allow for the SIDBlaster library, that was blocked before.
Please restart JSIDPlay2, now.

In your tool bar the tool bar should display SIDBlaster instead of emulation now.
Please check, that your console view and terminal does not show any error messages regarding the SIDBlaster library.
Then we are fine until here.

Then we can let JSIDPlay2 auto-detect all connected SIDBlaster devices,
therefore click on the SIDBlaster settings in the tool bar to expand all available SIDBlaster settings.
There is a magic wand to click. At the end it adds all detected SIDBlaster devices to your configuration.

All SIDBlaster devices will display a serial number and a chip type, which is still unknown (it is not stored on the hardware device, yet).
Therefore select the suitable SID chip model installed on your SIDBlaster device.
Now we are ready to test is using the Play button near the serial number to test each detected device.
Does it play? Then we are fine.

=== SIDBlaster tool

The purpose of that tool is to communicate with the device for administrative reasons
or to prepare the permanent usage inside JSIDPlay2 or other projects.

JSIDPlay2 ships with a sidblaster tool to change device settings,
that is namely the serial number and the SID chip type.
You can permanently store the SID chip type to be auto-detected by JSIDPlay2.

[source,subs="attributes+"]
----
cd /Users/<name>/Downloads/jsidplay2-4.3-java11-mac
chmod +x "SIDBlasterTool.sh"
"./SIDBlasterTool.sh"										 # <1>
"./SIDBlasterTool.sh" -c INFO								 # <2>
"./SIDBlasterTool.sh" -c SET_SID_TYPE -d 0 -t SIDTYPE_6581	 # <3>
"./SIDBlasterTool.sh" -c SET_SERIAL -d 0 -s A12B34C56D		 # <4>
"./SIDBlasterTool.sh" -c RUN_ON_WINDOWS -d 0				 # <5>
----
<1> Display usage
<2> List detected devices
<3> Example to set SID chip type
<4> Example to set serial number
<5> Example to use SIDBlaster only on Windows

=== Developer Instructions

...TODO...
Windows:
1. Install sidblaster sources
https://github.com/kenchis/SIDBlasterUSB_HardSID-emulation-driver
!!! Click on branch master and change to "apple" branch
Click on Code combobox
Click on download ZIP

2. https://cmake.org/download
cmake-3.20.3-windows-x86_64.msi

Eingabeaufforderung
cd /Users/<name>/Downloads/SIDBlasterUSB_HardSID-emulation-driver-apple
mkdir build
cd build

cmake ..

3. Visual Studio Community Edition installieren
https://visualstudio.microsoft.com/de/vs/community/

Explorer: 
/Users/<name>/Downloads/SIDBlasterUSB_HardSID-emulation-driver-apple/build/hardsid.sln öffnen

Toolbar: Release x64
cd /Users/<name>/Downloads/SIDBlasterUSB_HardSID-emulation-driver-apple/build/Release
hardsid.dll

dir hardsid.dll

Put it into JSIDPlay2:
copy hardsid.dll to src/main/resources/win32-x86-64/hardsid.dll

=== User Instructions

...TODO...

1.
Install Java
https://adoptopenjdk.net
Choose OpenJDT11 Hotspot
Neue Eingabeaufforderung
Type "java -version"

2.
Download JSIDPlay2, extract
Explorer: /Users/<name>/Downloads/jsidplay2-4.3-java11-win/jsidplay2-4.3-java11-win
SIDBlaster Geräte verbinden
Das Gerät ist einsatzbereit...
jsidplay2-4.3.exe
In ToolBar: Change Emulation to SIDBlaster

ToolBar: Click on SIDBlaster to expand devices list (still empty)
Click the magic wand
You should see a device list. The chip type could not be detected? see next section
Click on "Test" to test each detected device



=== Developer Instructions

...TODO...
Linux:
1.
Install ftd2xx drivers
https://ftdichip.com
Drivers/D2XX Drivers
Linux 1.4.24
tar xfvz libftd2xx-x86_64-1.4.24.gz
cd /home/<name>/Downloads/release/build
cp libftd2xx.1.4.24.so /usr/local/lib
cd ..
cp ftd2xx.h /usr/local/include
cd /usr/local/lib
ln -s libftd2xx.1.4.24.so libftd2xx.so
chmod 755 libftd2xx.1.4.24.so
chmod 755 libftd2xx.so
cd ../include
chmod 755 ftd2xx.h

2. Install sidblaster sources
https://github.com/kenchis/SIDBlasterUSB_HardSID-emulation-driver
!!! Click on branch master and change to "apple" branch
Click on Code combobox
Click on download ZIP

Ubuntu Software
cmake Cross-platform build system

cd /home/<name>/Downloads/SIDBlasterUSB_HardSID-emulation-driver-apple
mkdir build
cd build
cmake ..

NO_CMAKE_CXX_COMPILER found
-> sudo apt-get install g++

make
ls libhardsid.so

Put it into JSIDPlay2:
cp libhardsid.so to src/main/resources/linux-x64-64/libhardsid.so


=== User Instructions

...TODO...

1.
Install Java
https://adoptopenjdk.net
Choose OpenJDT11 Hotspot

tar xzvf OpenJDK11U-jdk_64_linux_hotspot_11.0.11_9.tar.gz
cd jdk-11.0.11+9/bin
Type "./java -version"


2.
Download JSIDPlay2
unzip /home/<name>/Downloads/jsidplay2-4.3-java11-linux.zip
cd /home/<name>/Downloads/jsidplay2-4.3-java11-linux
chmod +x "JSIDPlay2 (Java11).sh"

sudo vi /etc/udev/rules.d/91-sidblaster.rules
ACTION=="add", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", MODE="0666",  RUN+="/bin/sh -c 'rmmod ftdi_sio && rmmod usbserial'"
sudo udevadm control --reload-rules && udevadm trigger

SIDBlaster Geräte verbinden
"./JSIDPlay2 (Java11).sh"
In ToolBar: Change Emulation to SIDBlaster

ToolBar: Click on SIDBlaster to expand devices list (still empty)
Click the magic wand
You should see a device list. The chip type could not be detected? see next section
Click on "Test" to test each detected device

