/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hardsid_builder_HardSID4U */

#ifndef _Included_hardsid_builder_HardSID4U
#define _Included_hardsid_builder_HardSID4U
#ifdef __cplusplus
extern "C" {
#endif

#undef EXPORT
#define EXPORT __declspec(dllexport) JNIEXPORT


/*
 * Class:     hardsid_builder_HardSID4U
 * Method:    HardSID_DeviceCount
 * Signature: ()I
 */
EXPORT jint JNICALL Java_hardsid_1builder_HardSID4U_HardSID_1DeviceCount
  (JNIEnv *, jobject);

/*
 * Class:     hardsid_builder_HardSID4U
 * Method:    HardSID_SIDCount
 * Signature: (I)I
 */
EXPORT jint JNICALL Java_hardsid_1builder_HardSID4U_HardSID_1SIDCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardsid_builder_HardSID4U
 * Method:    HardSID_Read
 * Signature: (III)I
 */
EXPORT jint JNICALL Java_hardsid_1builder_HardSID4U_HardSID_1Read
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     hardsid_builder_HardSID4U
 * Method:    HardSID_Write
 * Signature: (IIII)V
 */
EXPORT void JNICALL Java_hardsid_1builder_HardSID4U_HardSID_1Write
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     hardsid_builder_HardSID4U
 * Method:    HardSID_Reset
 * Signature: (I)V
 */
EXPORT void JNICALL Java_hardsid_1builder_HardSID4U_HardSID_1Reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardsid_builder_HardSID4U
 * Method:    HardSID_Delay
 * Signature: (II)V
 */
EXPORT void JNICALL Java_hardsid_1builder_HardSID4U_HardSID_1Delay
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hardsid_builder_HardSID4U
 * Method:    HardSID_Flush
 * Signature: (I)V
 */
EXPORT void JNICALL Java_hardsid_1builder_HardSID4U_HardSID_1Flush
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
